# Generated by Django 4.2.7 on 2024-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foods_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='img',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
